### ISSUE TITLE
Get in touch with the GEM authors and discuss their contribution

### ISSUE THREAD

**Issue by sebrauschert** [Hobbeist/shinyGEM#7]
- Original author Joanna Holbrook does not have the time to commit to this but was very happy for us to continue the work.

- Pan Hong won't be able to commit to developing the package, but agreed to review and comment upon finalisation

**Comment by gopalmnair** [comment]
Gaby said all the three possible journals has latex template for paper. So I will use latex - I have asked Gabby to review the most suitable journal - then I will use their template -  it is not hard to change to other journal templates, if we decide to go for other.

**Comment by sebrauschert** [comment]
Sounds good to me Gopal. Thanks!
